---
    - name: Install Mysql-Server and zabbix-server
      yum: name={{ item }} state=latest
      with_items:
        - mariadb-server
        - zabbix-server-mysql
        - zabbix-web-mysql
    - name: start mysql-server
      service: name=mariadb state=started enabled=yes
    - name: set mysql admin password
      shell: /usr/bin/mysqladmin -u root password 'ansible'
    - name: create zabbix master databases
      shell: mysql -u root -pansible -e 'create database zabbix_master character set utf8 collate utf8_bin;'
    - name: set zabbix master databases
      shell: mysql -u root -pansible -e 'grant all privileges on zabbix_master.* to zabbix@localhost identified by "master";'
    - name: Import zabbix initial data
      shell: zcat create.sql.gz |mysql -uzabbix -uzabbix -pmaster zabbix_master chdir=/usr/share/doc/zabbix-server-mysql-3.0.11/
    - name: Change time zone
#      shell: sed -i 's#\# php_value date.timezone Europe/Riga#php_value date.timezone Asia/Shanghai#g' /etc/httpd/conf.d/zabbix.conf
    - name: Copy /etc/zabbix/zabbix_server.conf files
      template: src=zabbix_server.conf dest=/etc/zabbix/zabbix_server.conf owner=root group=root mode=644
    - name: Start zabbix-server and httpd
      service: name={{ item }} state=started enabled=yes
      with_items:
        - zabbix-server
        - httpd
