---
  - name: set hostname
    hostname: name={{ hostname }}

  - name: Stop firewalld
    service: name=firewalld state=stopped enabled=no

  - name: disable selinux
    shell: /usr/sbin/setenforce 0 && sed -i 's/SELINUX=enforcing/SELINUX=disabled/g' /etc/selinux/config

  - name: Install libselinux-python
    yum: name=libselinux-python

  - name: add zabbix yum source
    rpm: name=http://repo.zabbix.com/zabbix/3.0/rhel/7/x86_64/zabbix-release-3.0-1.el7.noarch.rpm
