---
    - name: Install Mysql-Server and zabbix-server
      yum: name={{ item }} state=latest
      with_items:
        - mariadb-server
        - zabbix-proxy-mysql
    - name: start mysql-server
      service: name=mariadb state=started enabled=yes
    - name: set mysql admin password
      shell: /usr/bin/mysqladmin -u root password 'ansible'
    - name: create zabbix proxy databases
      shell: mysql -u root -pansible -e 'create database zabbix_proxy character set utf8 collate utf8_bin;'
    - name: set zabbix master databases
      shell: mysql -u root -pansible -e 'grant all privileges on zabbix_proxy.* to zabbix@localhost identified by "proxy";'
    - name: Import zabbix initial data
      shell: zcat schema.sql.gz|mysql -uzabbix -pproxy zabbix_proxy chdir=/usr/share/doc/zabbix-proxy-mysql-3.0.11/
    - name: Copy /etc/zabbix/zabbix_proxy.conf files
      template: src=zabbix_proxy.conf dest=/etc/zabbix/zabbix_proxy.conf owner=root group=root mode=644
    - name: Start zabbix-proxy and httpd
      service: name={{ item }} state=started enabled=yes
      with_items:
        - zabbix-proxy
